# Generated by Django 2.0.5 on 2018-09-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(unique=True)),
                ('user_id', models.TextField(unique=True)),
            ],
        ),
    ]
